/** Every TanStack Query key in one place. */
export const qk = {
  session: () => ["session"] as const,
  setupStatus: () => ["setup-status"] as const,
  members: (archived = false) => ["members", archived] as const,
  settings: () => ["settings"] as const,
  devices: () => ["devices"] as const,
  diagnostics: () => ["diagnostics"] as const,
  backups: () => ["backups"] as const,
  kioskLayout: () => ["kiosk-layout"] as const,
  plugins: () => ["plugins"] as const,
  pluginSettings: (id: string) => ["plugins", id, "settings"] as const,
  photos: (kind: string) => ["photos", kind] as const,
  allowlist: () => ["network-allowlist"] as const,
  calendars: (removed = false) => ["calendars", removed] as const,
  occurrences: (from: string, to: string) => ["occurrences", from, to] as const,
  event: (id: string) => ["event", id] as const,
  removedEvents: () => ["events-removed"] as const,
  eventSearch: (query: string) => ["event-search", query] as const,
  syncAccounts: () => ["calendar-sync", "accounts"] as const,
  syncRuns: (accountId: string) => ["calendar-sync", "runs", accountId] as const,
  holidayPlaces: () => ["calendar-sync", "places"] as const,
};
