/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backups */
        get: operations["backups_api_admin_backups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/backups/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Backup */
        post: operations["run_backup_api_admin_backups_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/backups/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Backup */
        get: operations["download_backup_api_admin_backups__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagnostics */
        get: operations["diagnostics_api_admin_diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/device/label": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Rename This Device
         * @description "Name this screen" right after pairing, or a phone's own name.
         */
        put: operations["rename_this_device_api_auth_device_label_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_auth_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/devices/sign-out-others": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign Out Others */
        post: operations["sign_out_others_api_auth_devices_sign_out_others_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Sign Out Device */
        delete: operations["sign_out_device_api_auth_devices__device_id__delete"];
        options?: never;
        head?: never;
        /** Update Device */
        patch: operations["update_device_api_auth_devices__device_id__patch"];
        trace?: never;
    };
    "/api/auth/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join With Code
         * @description Sign in a new phone with a code from a signed-in device. Wrong codes count as wrong
         *     passwords do, so codes can't be guessed.
         */
        post: operations["join_with_code_api_auth_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/join-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make Join Code
         * @description Add a phone: a one-time code another phone signs in with. On a wall screen, which anyone
         *     in the house can reach, only a parent may make one.
         */
        post: operations["make_join_code_api_auth_join_codes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/kiosk/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pair
         * @description A parent's phone claims the code the screen shows.
         */
        post: operations["pair_api_auth_kiosk_pair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/kiosk/pair-with-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pair With Password
         * @description Typed on the screen itself, when no phone is at hand.
         */
        post: operations["pair_with_password_api_auth_kiosk_pair_with_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/kiosk/pairings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Pairing */
        post: operations["start_pairing_api_auth_kiosk_pairings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/kiosk/pairings/{poll_token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll Pairing */
        get: operations["poll_pairing_api_auth_kiosk_pairings__poll_token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/member": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Choose Member
         * @description Who's using this phone? A wall screen is everyone's: it picks a person per action.
         */
        put: operations["choose_member_api_auth_member_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Pin
         * @description Set or change the PIN. Where the PIN is what made this device a parent (the wall screen, a
         *     kid's phone), changing it asks for the current one; a parent's own phone doesn't need it, so
         *     a forgotten PIN can always be reset from there.
         */
        put: operations["set_pin_api_auth_pin_put"];
        post?: never;
        /** Remove Pin */
        delete: operations["remove_pin_api_auth_pin_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/pin/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lock
         * @description End this device's parent grant now (the display's Lock button).
         */
        post: operations["lock_api_auth_pin_lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/pin/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Parent Pin
         * @description A correct PIN unlocks parent things on this device for 10 minutes (no sliding).
         */
        post: operations["verify_parent_pin_api_auth_pin_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kiosk/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kiosk Command
         * @description Tell every wall screen to do something now (wall screens act; phones ignore it).
         */
        post: operations["kiosk_command_api_kiosk_command_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kiosk/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Layout */
        get: operations["get_layout_api_kiosk_layout_get"];
        /** Set Layout */
        put: operations["set_layout_api_kiosk_layout_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_members_get"];
        put?: never;
        /** Create Member */
        post: operations["create_member_api_members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Member */
        patch: operations["update_member_api_members__member_id__patch"];
        trace?: never;
    };
    "/api/members/{member_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Member */
        post: operations["archive_member_api_members__member_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{member_id}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Avatar
         * @description The picture is the request body (JPEG, PNG, WebP, HEIC), up to 15 MB.
         */
        put: operations["set_avatar_api_members__member_id__avatar_put"];
        post?: never;
        /** Remove Avatar */
        delete: operations["remove_avatar_api_members__member_id__avatar_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{member_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Member */
        post: operations["restore_member_api_members__member_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/network-allowlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Allowlist */
        get: operations["list_allowlist_api_network_allowlist_get"];
        put?: never;
        /** Add Allowlist */
        post: operations["add_allowlist_api_network_allowlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/network-allowlist/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Allowlist */
        delete: operations["remove_allowlist_api_network_allowlist__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Photos
         * @description Newest first, a page at a time; ``cursor`` is the last id of the previous page.
         */
        get: operations["list_photos_api_photos_get"];
        put?: never;
        /** Upload Photo */
        post: operations["upload_photo_api_photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Photo */
        get: operations["get_photo_api_photos__photo_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Photo
         * @description Removed with Undo: the row and files stay for 7 days (POST …/restore brings it back).
         */
        delete: operations["delete_photo_api_photos__photo_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{photo_id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hide Photo
         * @description Hide from the screensaver (the display can hide photos but never delete them).
         */
        post: operations["hide_photo_api_photos__photo_id__hide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{photo_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Photo */
        post: operations["restore_photo_api_photos__photo_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plugins */
        get: operations["list_plugins_api_plugins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{plugin_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable */
        post: operations["disable_api_plugins__plugin_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{plugin_id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable */
        post: operations["enable_api_plugins__plugin_id__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{plugin_id}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart */
        post: operations["restart_api_plugins__plugin_id__restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{plugin_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_plugins__plugin_id__settings_get"];
        /** Put Settings */
        put: operations["put_settings_api_plugins__plugin_id__settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_api_settings_patch"];
        trace?: never;
    };
    "/api/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Setup */
        post: operations["run_setup_api_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Setup Status */
        get: operations["setup_status_api_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AllowEntryIn */
        AllowEntryIn: {
            /**
             * Label
             * @default
             */
            label: string;
            /** Target */
            target: string;
        };
        /** AllowEntryOut */
        AllowEntryOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Target */
            target: string;
        };
        /** BackupFileOut */
        BackupFileOut: {
            /** Bytes */
            bytes: number;
            /** Name */
            name: string;
        };
        /** BackupRunOut */
        BackupRunOut: {
            /** Bytes */
            bytes: number;
            /** File */
            file: string;
            /** Seconds */
            seconds: number;
        };
        /** BackupStatusOut */
        BackupStatusOut: {
            /** Directory */
            directory: string;
            /** Files */
            files: components["schemas"]["BackupFileOut"][];
            /** Last Error */
            last_error: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Retention */
            retention: string;
            /** Schedule */
            schedule: string;
            /** Stale */
            stale: boolean;
        };
        /** ClientInfo */
        ClientInfo: {
            /** Host */
            host: string;
            /** Resolved Ip */
            resolved_ip: string | null;
            /** Scheme */
            scheme: string;
            /** Trusted Proxies Configured */
            trusted_proxies_configured: boolean;
            /** X Forwarded For */
            x_forwarded_for: string | null;
            /** X Forwarded Proto */
            x_forwarded_proto: string | null;
        };
        /** ContributesOut */
        ContributesOut: {
            /** Banners */
            banners: string[];
            /** Display Overlay */
            display_overlay: boolean;
            /** Display Panels */
            display_panels: components["schemas"]["PanelOut"][];
            /** Display Rooms */
            display_rooms: components["schemas"]["RoomOut"][];
            /** Phone Tabs */
            phone_tabs: components["schemas"]["TabOut"][];
            /** Settings Sections */
            settings_sections: components["schemas"]["SectionOut"][];
        };
        /** DeviceLabelIn */
        DeviceLabelIn: {
            /** Label */
            label: string;
        };
        /** DeviceOut */
        DeviceOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Is Current */
            is_current: boolean;
            /** Is Kid Device */
            is_kid_device: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "phone" | "kiosk";
            /** Label */
            label: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Member Name */
            member_name: string | null;
        };
        /** DeviceUpdate */
        DeviceUpdate: {
            /** Is Kid Device */
            is_kid_device?: boolean | null;
            /** Label */
            label?: string | null;
        };
        /** DiagnosticsOut */
        DiagnosticsOut: {
            backups: components["schemas"]["BackupStatusOut"];
            client: components["schemas"]["ClientInfo"];
            /** Install Kind */
            install_kind: string;
            live_updates: components["schemas"]["LiveUpdatesInfo"];
            /** Plugins */
            plugins: components["schemas"]["PluginInfo"][];
            /** Recent Addresses */
            recent_addresses: string[];
            /** Revision */
            revision: string;
            /** Schema Revision */
            schema_revision: string | null;
            storage: components["schemas"]["StorageInfo"];
            /** Timezone */
            timezone: string;
            /** Version */
            version: string;
        };
        /** FieldOut */
        FieldOut: {
            /** Choice Labels */
            choice_labels: string[] | null;
            /** Choices */
            choices: string[] | null;
            /** Default */
            default: unknown;
            /** Group */
            group: string;
            /** Help */
            help: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Max */
            max: number | null;
            /** Max Length */
            max_length: number | null;
            /** Min */
            min: number | null;
            /** Required */
            required: boolean;
            /** Step */
            step: number | null;
            /** Type */
            type: string;
            /** Unit */
            unit: string | null;
        };
        /** GrantOut */
        GrantOut: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
        };
        /** JoinCodeOut */
        JoinCodeOut: {
            /** Code */
            code: string;
            /** Display */
            display: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Url */
            url: string;
        };
        /** JoinIn */
        JoinIn: {
            /** Code */
            code: string;
        };
        /** KioskCommandIn */
        KioskCommandIn: {
            /**
             * Command
             * @enum {string}
             */
            command: "reload" | "wake" | "screensaver" | "show_event";
            /** Event Key */
            event_key?: string | null;
        };
        /** KioskLayoutIn */
        KioskLayoutIn: {
            /** Panels */
            panels: components["schemas"]["KioskPanelIn"][];
        };
        /** KioskPairIn */
        KioskPairIn: {
            /** Code */
            code: string;
            /**
             * Label
             * @default Kitchen screen
             */
            label: string;
        };
        /** KioskPairingOut */
        KioskPairingOut: {
            /** Code */
            code: string;
            /** Display */
            display: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Expires In */
            expires_in: number;
            /** Pair Url */
            pair_url: string;
            /** Poll Token */
            poll_token: string;
        };
        /** KioskPanelIn */
        KioskPanelIn: {
            /** Key */
            key: string;
            /**
             * Size
             * @default m
             * @enum {string}
             */
            size: "s" | "m" | "l";
            /**
             * Visible
             * @default true
             */
            visible: boolean;
        };
        /** KioskPanelOut */
        KioskPanelOut: {
            /** Key */
            key: string;
            /** Position */
            position: number;
            /**
             * Size
             * @enum {string}
             */
            size: "s" | "m" | "l";
            /** Visible */
            visible: boolean;
        };
        /** KioskPasswordPairIn */
        KioskPasswordPairIn: {
            /**
             * Label
             * @default Kitchen screen
             */
            label: string;
            /** Password */
            password: string;
        };
        /** KioskPollOut */
        KioskPollOut: {
            session?: components["schemas"]["SessionOut"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "waiting" | "paired" | "expired";
        };
        /** LiveUpdatesInfo */
        LiveUpdatesInfo: {
            /** Connections */
            connections: number;
            /** Epoch */
            epoch: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Password */
            password: string;
        };
        /** MemberChoice */
        MemberChoice: {
            /** Member Id */
            member_id: string | null;
        };
        /** MemberCreate */
        MemberCreate: {
            /** Birthday */
            birthday?: string | null;
            /** Color */
            color?: ("clay" | "olive" | "moss" | "sea" | "sky" | "iris" | "berry" | "rose") | null;
            /** Name */
            name: string;
            /**
             * Role
             * @default parent
             * @enum {string}
             */
            role: "parent" | "kid";
        };
        /** MemberOut */
        MemberOut: {
            /** Archived */
            archived: boolean;
            /** Avatar Url */
            avatar_url: string | null;
            /** Birthday */
            birthday: string | null;
            /**
             * Color
             * @enum {string}
             */
            color: "clay" | "olive" | "moss" | "sea" | "sky" | "iris" | "berry" | "rose";
            /** Color Word */
            color_word: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "parent" | "kid";
        };
        /** MemberUpdate */
        MemberUpdate: {
            /** Birthday */
            birthday?: string | null;
            /** Color */
            color?: ("clay" | "olive" | "moss" | "sea" | "sky" | "iris" | "berry" | "rose") | null;
            /** Name */
            name?: string | null;
            /** Role */
            role?: ("parent" | "kid") | null;
        };
        /** PanelOut */
        PanelOut: {
            /** Default Size */
            default_size: string;
            /** Key */
            key: string;
            /** Requires Member */
            requires_member: boolean;
            /** Sizes */
            sizes: string[];
            /** Title */
            title: string;
        };
        /** PhotoOut */
        PhotoOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Height */
            height: number;
            /** Hidden */
            hidden: boolean;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "library" | "avatar";
            /** Taken At */
            taken_at: string | null;
            /** Thumb Url */
            thumb_url: string;
            /** Url */
            url: string;
            /** Width */
            width: number;
        };
        /** PhotoPage */
        PhotoPage: {
            /** Next Cursor */
            next_cursor: string | null;
            /** Photos */
            photos: components["schemas"]["PhotoOut"][];
        };
        /** PinSetIn */
        PinSetIn: {
            /** Current Pin */
            current_pin?: string | null;
            /** Pin */
            pin: string;
        };
        /** PinVerifyIn */
        PinVerifyIn: {
            /** Pin */
            pin: string;
        };
        /** PluginInfo */
        PluginInfo: {
            /** Error */
            error: string | null;
            /** Id */
            id: string;
            /** Status */
            status: string;
        };
        /** PluginOut */
        PluginOut: {
            contributes: components["schemas"]["ContributesOut"];
            /** Description */
            description: string;
            /** Enabled */
            enabled: boolean;
            /** Error */
            error: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Requires Parent To Manage */
            requires_parent_to_manage: boolean;
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
            /** Settings Spec */
            settings_spec: components["schemas"]["FieldOut"][];
            /**
             * Status
             * @enum {string}
             */
            status: "disabled" | "starting" | "running" | "errored" | "stopping";
            /** Url Prefix */
            url_prefix: string;
            /** Version */
            version: string;
        };
        /** RoomOut */
        RoomOut: {
            /** Icon */
            icon: string;
            /** Key */
            key: string;
            /** Order */
            order: number;
            /** Title */
            title: string;
        };
        /** SectionOut */
        SectionOut: {
            /** Key */
            key: string;
            /** Parent Only */
            parent_only: boolean;
            /** Title */
            title: string;
        };
        /** SessionOut */
        SessionOut: {
            /** Device Id */
            device_id: string;
            /**
             * Device Kind
             * @enum {string}
             */
            device_kind: "phone" | "kiosk";
            /** Device Label */
            device_label: string;
            /** Grant Expires At */
            grant_expires_at: string | null;
            /** Has Pin */
            has_pin: boolean;
            /** Household Name */
            household_name: string;
            /** Is Kid Device */
            is_kid_device: boolean;
            /** Is Parent */
            is_parent: boolean;
            member: components["schemas"]["MemberOut"] | null;
            /** Members */
            members: components["schemas"]["MemberOut"][];
            /** Pin Length */
            pin_length: number | null;
        };
        /** SettingsIn */
        SettingsIn: {
            /** Values */
            values: {
                [key: string]: unknown;
            };
        };
        /** SettingsOut */
        SettingsOut: {
            /** Daylight Tint */
            daylight_tint: boolean;
            /** Display Controls Bottom */
            display_controls_bottom: boolean;
            /** Display Dim Past */
            display_dim_past: boolean;
            /**
             * Display Home View
             * @enum {string}
             */
            display_home_view: "week" | "today" | "people";
            /**
             * Display Orientation
             * @enum {string}
             */
            display_orientation: "auto" | "landscape" | "portrait";
            /**
             * Display Rail Side
             * @enum {string}
             */
            display_rail_side: "left" | "right";
            /** Display Reduce Motion */
            display_reduce_motion: boolean;
            /** Display Return Minutes */
            display_return_minutes: number;
            /** Display Show Today Panel */
            display_show_today_panel: boolean;
            /** Display Sounds */
            display_sounds: boolean;
            /** Has Pin */
            has_pin: boolean;
            /** Household Name */
            household_name: string;
            /** Kid Safe Editing */
            kid_safe_editing: boolean;
            /** Latitude */
            latitude: number | null;
            /** Location Label */
            location_label: string | null;
            /** Longitude */
            longitude: number | null;
            /** Pin Length */
            pin_length: number | null;
            /** Setup Complete */
            setup_complete: boolean;
            /** Sleep From */
            sleep_from: string | null;
            /**
             * Sleep Mode
             * @enum {string}
             */
            sleep_mode: "dim_clock" | "screen_off";
            /** Sleep To */
            sleep_to: string | null;
            /**
             * Text Size
             * @enum {string}
             */
            text_size: "standard" | "large" | "xl";
            /**
             * Theme
             * @enum {string}
             */
            theme: "auto" | "light" | "dark";
            /**
             * Time Format
             * @enum {string}
             */
            time_format: "12h" | "24h";
            /** Timezone */
            timezone: string;
            /** Timezone Chosen */
            timezone_chosen: boolean;
            /** Week Starts On */
            week_starts_on: number;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Daylight Tint */
            daylight_tint?: boolean | null;
            /** Display Controls Bottom */
            display_controls_bottom?: boolean | null;
            /** Display Dim Past */
            display_dim_past?: boolean | null;
            /** Display Home View */
            display_home_view?: ("week" | "today" | "people") | null;
            /** Display Orientation */
            display_orientation?: ("auto" | "landscape" | "portrait") | null;
            /** Display Rail Side */
            display_rail_side?: ("left" | "right") | null;
            /** Display Reduce Motion */
            display_reduce_motion?: boolean | null;
            /** Display Return Minutes */
            display_return_minutes?: (0 | 2 | 5 | 10) | null;
            /** Display Show Today Panel */
            display_show_today_panel?: boolean | null;
            /** Display Sounds */
            display_sounds?: boolean | null;
            /** Household Name */
            household_name?: string | null;
            /** Kid Safe Editing */
            kid_safe_editing?: boolean | null;
            /** Latitude */
            latitude?: number | null;
            /** Location Label */
            location_label?: string | null;
            /** Longitude */
            longitude?: number | null;
            /** Sleep From */
            sleep_from?: string | null;
            /** Sleep Mode */
            sleep_mode?: ("dim_clock" | "screen_off") | null;
            /** Sleep To */
            sleep_to?: string | null;
            /** Text Size */
            text_size?: ("standard" | "large" | "xl") | null;
            /** Theme */
            theme?: ("auto" | "light" | "dark") | null;
            /** Time Format */
            time_format?: ("12h" | "24h") | null;
            /** Timezone */
            timezone?: string | null;
            /** Week Starts On */
            week_starts_on?: number | null;
        };
        /** SetupIn */
        SetupIn: {
            /** Household Name */
            household_name: string;
            /** Password */
            password: string;
            /**
             * Time Format
             * @default 12h
             * @enum {string}
             */
            time_format: "12h" | "24h";
            /** Timezone */
            timezone: string;
            /**
             * Week Starts On
             * @default 6
             */
            week_starts_on: number;
        };
        /** SetupStatusOut */
        SetupStatusOut: {
            /** Advertised Url */
            advertised_url: string;
            /** Password From Env */
            password_from_env: boolean;
            /** Server Timezone */
            server_timezone: string | null;
            /** Setup Complete */
            setup_complete: boolean;
            /** Version */
            version: string;
        };
        /** SignOutOthersIn */
        SignOutOthersIn: {
            /**
             * Include Kiosks
             * @default false
             */
            include_kiosks: boolean;
        };
        /** StorageInfo */
        StorageInfo: {
            /** Free Bytes */
            free_bytes: number;
            /** Total Bytes */
            total_bytes: number;
        };
        /** TabOut */
        TabOut: {
            /** Icon */
            icon: string;
            /** Key */
            key: string;
            /** Order */
            order: number;
            /** Path */
            path: string;
            /** Title */
            title: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionOut */
        VersionOut: {
            /** Created */
            created: string | null;
            /** Revision */
            revision: string;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    backups_api_admin_backups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupStatusOut"];
                };
            };
        };
    };
    run_backup_api_admin_backups_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupRunOut"];
                };
            };
        };
    };
    download_backup_api_admin_backups__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnostics_api_admin_diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsOut"];
                };
            };
        };
    };
    rename_this_device_api_auth_device_label_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceLabelIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_auth_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"][];
                };
            };
        };
    };
    sign_out_others_api_auth_devices_sign_out_others_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignOutOthersIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_out_device_api_auth_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_device_api_auth_devices__device_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_with_code_api_auth_join_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    make_join_code_api_auth_join_codes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinCodeOut"];
                };
            };
        };
    };
    pair_api_auth_kiosk_pair_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KioskPairIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pair_with_password_api_auth_kiosk_pair_with_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KioskPasswordPairIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_pairing_api_auth_kiosk_pairings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KioskPairingOut"];
                };
            };
        };
    };
    poll_pairing_api_auth_kiosk_pairings__poll_token__get: {
        parameters: {
            query?: {
                wait?: number;
            };
            header?: never;
            path: {
                poll_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KioskPollOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    choose_member_api_auth_member_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberChoice"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_pin_api_auth_pin_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinSetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_pin_api_auth_pin_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    lock_api_auth_pin_lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_parent_pin_api_auth_pin_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinVerifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    export_api_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    kiosk_command_api_kiosk_command_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KioskCommandIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_layout_api_kiosk_layout_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KioskPanelOut"][];
                };
            };
        };
    };
    set_layout_api_kiosk_layout_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KioskLayoutIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KioskPanelOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_members_get: {
        parameters: {
            query?: {
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_member_api_members_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_api_members__member_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_member_api_members__member_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_avatar_api_members__member_id__avatar_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_avatar_api_members__member_id__avatar_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_member_api_members__member_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_allowlist_api_network_allowlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllowEntryOut"][];
                };
            };
        };
    };
    add_allowlist_api_network_allowlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllowEntryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllowEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_allowlist_api_network_allowlist__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_photos_api_photos_get: {
        parameters: {
            query?: {
                kind?: "library" | "avatar";
                source?: string | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_photo_api_photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoOut"];
                };
            };
        };
    };
    get_photo_api_photos__photo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_photo_api_photos__photo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hide_photo_api_photos__photo_id__hide_post: {
        parameters: {
            query?: {
                hidden?: boolean;
            };
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_photo_api_photos__photo_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plugins_api_plugins_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginOut"][];
                };
            };
        };
    };
    disable_api_plugins__plugin_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plugin_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_api_plugins__plugin_id__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plugin_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_api_plugins__plugin_id__restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plugin_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_plugins__plugin_id__settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plugin_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_settings_api_plugins__plugin_id__settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plugin_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    update_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_setup_api_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setup_status_api_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
        };
    };
    version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"];
                };
            };
        };
    };
}
